name: HeartMe
main: HeartMe\Loader
version: 1.0.0
api: [1.0.0]
load: POSTWORLD
author: Gamecrafter
description: Players can date each other for roleplay!
website: https://github.com/Gamecrafter/HeartMe
commands:
 date:
  description: Dates the specified player
  usage: /date <player>
  permission: heartme.command.date
 dump:
  description: Dump the specified player
  usage: /dump <player>
  permission: heartme.command.dump
